//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISQuangNam.DataProvider.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GISEntities : DbContext
    {
        public GISEntities()
            : base("name=GISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<THONGTINDOAN> THONGTINDOANs { get; set; }
        public virtual DbSet<YKienQuyHoach> YKienQuyHoaches { get; set; }
        public virtual DbSet<QHCT_SUDUNGDAT> QHCT_SUDUNGDAT { get; set; }
        public virtual DbSet<QHPK_SUDUNGDAT> QHPK_SUDUNGDAT { get; set; }
        public virtual DbSet<HoSoDoAn> HoSoDoAns { get; set; }
        public virtual DbSet<KHAC_THONGTINDOAN> KHAC_THONGTINDOAN { get; set; }
        public virtual DbSet<QHC_THONGTINDOAN> QHC_THONGTINDOAN { get; set; }
        public virtual DbSet<QHCT_THONGTINDOAN> QHCT_THONGTINDOAN { get; set; }
        public virtual DbSet<QHNT_THONGTINDOAN> QHNT_THONGTINDOAN { get; set; }
        public virtual DbSet<QHPK_THONGTINDOAN> QHPK_THONGTINDOAN { get; set; }
        public virtual DbSet<QHV_THONGTINDOAN> QHV_THONGTINDOAN { get; set; }
    }
}
