//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISQuangNam.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoDoAn
    {
        public int id { get; set; }
        public string MaDoAn { get; set; }
        public string TenHoSo { get; set; }
        public string LoaiHoSo { get; set; }
        public string DinhDangHoSo { get; set; }
        public string DuongDan { get; set; }
    }
}
