//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISQuangNam.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QHC_THONGTINDOAN
    {
        public int OBJECTID { get; set; }
        public string MaDoAn { get; set; }
        public string TenDoAn { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public string DonViCapNhat { get; set; }
        public string DonViQuanLy { get; set; }
        public string GhiChu { get; set; }
        public string KiHieuKhuVuc { get; set; }
        public string ChuDauTu { get; set; }
        public string SoQuyetDinhPheDuyet { get; set; }
        public Nullable<System.DateTime> NgayPheDuyet { get; set; }
        public string CoQuanPheDuyet { get; set; }
        public string MaQuanHuyen { get; set; }
        public string MaPhuongXa { get; set; }
        public string LoaiQuyHoach { get; set; }
        public string TrangThaiDoAn { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
