//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISQuangNam.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QHPK_SUDUNGDAT
    {
        public int OBJECTID { get; set; }
        public string MaSDD { get; set; }
        public string KiHieuKhuDat { get; set; }
        public string LoaiDat { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public string MatDoXayDung { get; set; }
        public string TangCao { get; set; }
        public string ChiGioiXayDung { get; set; }
        public string KhoangLuiBien { get; set; }
        public string GhiChu { get; set; }
        public string ChucNang { get; set; }
        public string GiaiDoanQuyHoach { get; set; }
        public string HeSoSuDungDat { get; set; }
        public string KhoangLuiChinh { get; set; }
        public string MaPhuongXa { get; set; }
        public string MaQuanHuyen { get; set; }
        public Nullable<decimal> KhoangCach_sanbaydanang { get; set; }
        public Nullable<decimal> KhoangCach_sanbaychulai { get; set; }
        public Nullable<decimal> KhoangCach_cangkyha { get; set; }
        public Nullable<decimal> KhoangCach_TpTamky { get; set; }
        public Nullable<decimal> KhoangCach_tphoian { get; set; }
        public Nullable<decimal> KhoangCach_cuakhaunamgiang { get; set; }
        public string TenDoAn { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
