//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGISQuangNam.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YKienQuyHoach
    {
        public int id { get; set; }
        public string TenToChu { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string NoiDungGopY { get; set; }
        public string MaDoAn { get; set; }
        public Nullable<System.DateTime> NgayLuu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string NoiDungTraLoi { get; set; }
        public string TenDoAn { get; set; }
        public string BangDuLieu { get; set; }
    }
}
